from typing import List

from PIL import Image, ImageDraw
from PIL.Image import Resampling

from ...models.chu_song import ChuSong
from ...score.chunithm import PlayerChuScore
from ..maimai._config import FONT_MAIN, FONT_NUM
from ..maimai._config import PIC_DIR as MAI_PIC_DIR
from ..utils import DrawText, change_column_width, coloum_width
from ._base import ScoreBaseImage
from ._config import COVER_DIR, GENRE_MAPPING, PIC_DIR


def draw_music_info(song: ChuSong, scores: List[PlayerChuScore]) -> Image.Image:
    """
    绘制单曲详情及成绩

    :param song: 乐曲信息
    :param scores: 玩家在该乐曲上的成绩列表
    :return: 绘制后的图片
    """
    im = Image.open(MAI_PIC_DIR / "info_bg.png").convert("RGBA")
    dr = ImageDraw.Draw(im)
    mr = DrawText(dr, FONT_MAIN)
    tb = DrawText(dr, FONT_NUM)
    default_color = (124, 130, 255, 255)

    im.alpha_composite(Image.open(PIC_DIR / "chunithm_cn_2026.png").resize((300, 300)), (35, -25))

    # Cover
    cover_path = COVER_DIR / f"{song.id}.png"
    dx_cover_path = COVER_DIR / f"{song.id + 10000}.png"
    if cover_path.exists():
        cover = Image.open(cover_path).resize((300, 300))
    elif dx_cover_path.exists():
        cover = Image.open(dx_cover_path).resize((300, 300))
    else:
        cover = Image.new("RGBA", (300, 300), (0, 0, 0, 0))
    im.alpha_composite(cover, (100, 260))

    # Genre
    genre_key = GENRE_MAPPING.get(song.genre, "game")
    genre_path = MAI_PIC_DIR / f"info-{genre_key}.png"
    if genre_path.exists():
        im.alpha_composite(Image.open(genre_path), (100, 260))

    # Version
    version_path = PIC_DIR / f"{song.version}.png"
    if version_path.exists():
        im.alpha_composite(Image.open(version_path).resize((183, 90)), (295, 205))

    # Artist & Title
    artist = song.artist
    if coloum_width(artist) > 58:
        artist = change_column_width(artist, 57) + "..."
    mr.draw(255, 595, 12, artist, default_color, "mm")

    title = song.title
    if coloum_width(title) > 38:
        title = change_column_width(title, 37) + "..."
    mr.draw(255, 622, 18, title, default_color, "mm")

    tb.draw(160, 720, 22, f"{song.id}", default_color, "mm")
    tb.draw(380, 720, 22, f"{song.bpm}", default_color, "mm")

    y = 100
    for num, diff in enumerate(song.difficulties.difficulties):
        if num >= 5:
            break

        im.alpha_composite(Image.open(MAI_PIC_DIR / f"d-{num}.png"), (650, 235 + y * num))

        score = next((s for s in scores if s.song_difficulty.value == num), None)

        if score:
            rank_badge = ScoreBaseImage._score_badge(score)
            rank_badge = rank_badge.resize((80, 23), Resampling.LANCZOS)
            im.alpha_composite(rank_badge, (1010, 290 + y * num))

            ach_badge = ScoreBaseImage._achievement_badge(score)
            if ach_badge:
                ach_badge = ach_badge.resize((80, 23), Resampling.LANCZOS)
                im.alpha_composite(ach_badge, (920, 290 + y * num))

            tb.draw(510, 292 + y * num, 42, f"{score.score:,}", default_color, "lm")
            tb.draw(685, 248 + y * num, 25, f"{diff.level_value}", (255, 255, 255, 255), "mm")
            tb.draw(750, 248 + y * num, 27, f"Rating: {score.rating:.2f}", default_color, "lm")

        else:
            tb.draw(685, 248 + y * num, 25, f"{diff.level_value}", (255, 255, 255, 255), "mm")
            mr.draw(800, 300 + y * num, 30, "未游玩", default_color, "mm")

    if len(song.difficulties.difficulties) == 4:
        mr.draw(800, 300 + y * 4, 30, "没有该难度", default_color, "mm")

    mr.draw(
        600, 827, 22, "Designed by Yuri-YuzuChaN & BlueDeer233. Generated by NoneBot-Plugin-Rikka", default_color, "mm"
    )

    return im
