"""add_chunithm_friend_code

迁移 ID: 37e7fa94eaec
父迁移: 5c791c303fe1
创建时间: 2026-06-06 02:07:52.897793

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "37e7fa94eaec"
down_revision: str | Sequence[str] | None = "dc59349a578a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_rikka_userbindinfo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mai_friend_code", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("chu_friend_code", sa.String(), nullable=True))

    # 数据迁移：将旧 friend_code 复制到 mai_friend_code
    op.execute(
        "UPDATE nonebot_plugin_rikka_userbindinfo "
        "SET mai_friend_code = friend_code "
        "WHERE friend_code IS NOT NULL AND friend_code != ''"
    )

    with op.batch_alter_table("nonebot_plugin_rikka_userbindinfo", schema=None) as batch_op:
        batch_op.drop_column("friend_code")

    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("nonebot_plugin_rikka_userbindinfo", schema=None) as batch_op:
        batch_op.add_column(sa.Column("friend_code", sa.VARCHAR(), nullable=True))
        batch_op.drop_column("chu_friend_code")
        batch_op.drop_column("mai_friend_code")

    # ### end Alembic commands ###
