"""add_chunithm_table

迁移 ID: d07c88373fbd
父迁移: 37e7fa94eaec
创建时间: 2026-06-09 22:01:07.075339

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d07c88373fbd"
down_revision: str | Sequence[str] | None = "37e7fa94eaec"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "nonebot_plugin_rikka_chusong",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("genre", sa.String(), nullable=False),
        sa.Column("bpm", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("difficulties", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_nonebot_plugin_rikka_chusong")),
        info={"bind_key": "nonebot_plugin_rikka"},
    )
    op.create_table(
        "nonebot_plugin_rikka_chusongalias",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("alias", sa.String(), nullable=True),
        sa.Column("custom_alias", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["nonebot_plugin_rikka_chusong.id"],
            name=op.f("fk_nonebot_plugin_rikka_chusongalias_song_id_nonebot_plugin_rikka_chusong"),
        ),
        sa.PrimaryKeyConstraint("song_id", name=op.f("pk_nonebot_plugin_rikka_chusongalias")),
        info={"bind_key": "nonebot_plugin_rikka"},
    )
    # ### end Alembic commands ###


def downgrade(name: str = "") -> None:
    if name:
        return
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("nonebot_plugin_rikka_chusongalias")
    op.drop_table("nonebot_plugin_rikka_chusong")
    # ### end Alembic commands ###
