[project]
name = "nonebot-plugin-rikka"
dynamic = ["version"]
description = "一个简简单单的舞萌机器人插件"
readme = "README.md"
requires-python = ">=3.9, <4.0"
dependencies = [
    "nonebot2>=2.4.1",
    "nonebot-adapter-onebot>=2.4.6",
    "nonebot2[fastapi,httpx,websockets]>=2.4.3",
    "aiohttp>=3.13.1",
    "nonebot-plugin-alconna>=0.59.4",
    "nonebot-plugin-orm[sqlite]>=0.8.2",
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.1.0",
    "mypy>=1.15.0",
    "black>=25.1.0",
    "types-PyYAML"
]

[tool.nonebot]
adapters = [
    { name = "OneBot V11", module_name = "nonebot.adapters.onebot.v11" }
]
plugins = ["rikka"]
builtin_plugins = []

[tool.black]
line-length = 120

[tool.isort]
profile = "black"

[tool.pdm]
distribution = true

[tool.pdm.version]
source = "scm"
tag_filter = "v*"
tag_regex = '^v(?:\D*)?(?P<version>([1-9][0-9]*!)?(0|[1-9][0-9]*)(\.(0|[1-9][0-9]*))*((a|b|c|rc)(0|[1-9][0-9]*))?(\.post(0|[1-9][0-9]*))?(\.dev(0|[1-9][0-9]*))?$)$'
fallback_version = "1.0.0"

[tool.pdm.build]
includes = []

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
